# Generated by Django 5.2.7 on 2025-11-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="class_codes",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
